//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cuoiki_LTWNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fine
    {
        public int FineID { get; set; }
        public Nullable<int> BorrowID { get; set; }
        public Nullable<decimal> FineAmount { get; set; }
        public Nullable<bool> PaidStatus { get; set; }
    
        public virtual Borrowing_Record Borrowing_Record { get; set; }
    }
}
