//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cuoiki_LTWNC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WNC_QUANLYTHIVIEN_REALEntities : DbContext
    {
        public WNC_QUANLYTHIVIEN_REALEntities()
            : base("name=WNC_QUANLYTHIVIEN_REALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Borrowing_Record> Borrowing_Record { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Fine> Fines { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Publisher> Publishers { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Staff_Add_Book> Staff_Add_Book { get; set; }
        public virtual DbSet<Student> Students { get; set; }
    }
}
