//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cuoiki_LTWNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> NotificationDate { get; set; }
        public Nullable<bool> ReadStatus { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
